module.exports = [
  {
    id: 1,
    username: "admin",
    first: "Вася",
    lastname: "Василек",
    city: "Moscow",
    avatar: "https://avatars.githubusercontent.com/u/16114823?v=4",
    age: "33",
    currency: "RUB",
    country: "Russia",
  },
  {
    id: 2,
    username: "user",
    first: "Ваня",
    lastname: "Иванов",
    city: "Moscow",
    avatar: "https://cdnn21.img.ria.ru/images/148588/80/1485888066_0:0:1575:1013_1440x900_80_0_1_b3c0bdbc235f3b6931a3cbbb8f7cf636.jpg.webp?source-sid=",
    age: "35",
    currency: "RUB",
    country: "Belarus",
  },
  {
    id: 3,
    username: "user1",
    first: "Алеша",
    lastname: "Попович",
    city: "Moscow",
    avatar: "https://disney-classic.ru/wp-content/uploads/maxresdefault.jpg",
    age: "35",
    currency: "RUB",
    country: "Russia",
  },
  {
    id: 4,
    username: "user2",
    first: "Никита",
    lastname: "Никитич",
    city: "Moscow",
    avatar: "https://disney-classic.ru/wp-content/uploads/AdventuresOfTheGummiBears-TheSinisterSculptor-Gruffi.png",
    age: "35",
    currency: "RUB",
    country: "Russia",
  },
  {
    id: 5,
    username: "user3",
    first: "Илья",
    lastname: "Ильин",
    city: "Moscow",
    avatar: "https://disney-classic.ru/wp-content/uploads/Launchpad6.jpg",
    age: "35",
    currency: "RUB",
    country: "Russia",
  },
  {
    id: 6,
    username: "user4",
    first: "Геннадий",
    lastname: "Геннадьевич",
    city: "Moscow",
    avatar: "https://static.mishka-knizhka.ru/wp-content/uploads/2021/08/chernyy-placsh.jpg.webp",
    age: "35",
    currency: "RUB",
    country: "Russia",
  },
  {
    id: 7,
    username: "user5",
    first: "Александр",
    lastname: "Александров",
    city: "Moscow",
    avatar: "https://media.2x2tv.ru/content/images/2021/02/np1.jpg",
    age: "35",
    currency: "RUB",
    country: "Russia",
  },
  {
    id: 8,
    username: "user6",
    first: "Виктор",
    lastname: "Викторов",
    city: "Moscow",
    avatar: "https://villib.ru/pics/mklass/2021/zmey/1mk181021.jpg",
    age: "35",
    currency: "RUB",
    country: "Russia",
  },
  {
    id: 9,
    username: "user7",
    first: "Володя",
    lastname: "Володин",
    city: "Moscow",
    avatar: "https://www.film.ru/sites/default/files/filefield_paths/9_1.jpg",
    age: "35",
    currency: "RUB",
    country: "Russia",
  },
  {
    id: 10,
    username: "user8",
    first: "Леонид",
    lastname: "Леонидов",
    city: "Moscow",
    avatar: "https://img.gazeta.ru/files3/283/12963283/MV5BYzg2ZWYyZTMtYTAwOS00NzU3LTg0YmQtZmNkODg5NzQ4Y2Y2XkEyXkFqcGdeQXVyMDM2NDM2MQ__._V1_SX1777_CR0_0_1777_738_AL_-pic905-895x505-39709.jpg",
    age: "35",
    currency: "RUB",
    country: "Russia",
  },
];
