module.exports = [
  {
    id: 1,
    username: "admin",
    password: "123",
    accessToken: "admin-123",
    role: "ADMIN",
  },
  {
    id: 2,
    username: "user",
    password: "123",
    accessToken: "user-123",
    role: "USER",
  },
  {
    id: 3,
    username: "user1",
    password: "123",
    accessToken: "user-123",
    role: "USER",
  },
  {
    id: 4,
    username: "user2",
    password: "123",
    accessToken: "user-123",
    role: "USER",
  },
  {
    id: 5,
    username: "user3",
    password: "123",
    accessToken: "user-123",
    role: "USER",
  },
  {
    id: 6,
    username: "user4",
    password: "123",
    accessToken: "user-123",
    role: "USER",
  },
  {
    id: 7,
    username: "user5",
    password: "123",
    accessToken: "user-123",
    role: "USER",
  },
  {
    id: 8,
    username: "user6",
    password: "123",
    accessToken: "user-123",
    role: "USER",
  },
  {
    id: 9,
    username: "user7",
    password: "123",
    accessToken: "user-123",
    role: "USER",
  },
  {
    id: 10,
    username: "user8",
    password: "123",
    accessToken: "user-123",
    role: "USER",
  },
];
