module.exports = [
  {
    id: 1,
    username: "admin",
    password: "123",
    accessToken: "accessToken-for-id-1",
    refreshToken: "refreshToken-for-id-1",
    role: "ADMIN",
  },
  {
    id: 2,
    username: "user",
    password: "123",
    accessToken: "accessToken-for-id-2",
    refreshToken: "refreshToken-for-id-2",
    role: "USER",
  },
  {
    id: 3,
    username: "manager",
    password: "123",
    accessToken: "accessToken-for-id-3",
    refreshToken: "refreshToken-for-id-3",
    role: "MANAGER",
  },
  {
    id: 4,
    username: "user2",
    password: "123",
    accessToken: "accessToken-for-id-4",
    refreshToken: "refreshToken-for-id-4",
    role: "USER",
  },
  {
    id: 5,
    username: "user3",
    password: "123",
    accessToken: "accessToken-for-id-5",
    refreshToken: "refreshToken-for-id-5",
    role: "USER",
  },
  {
    id: 6,
    username: "user4",
    password: "123",
    accessToken: "accessToken-for-id-6",
    refreshToken: "refreshToken-for-id-6",
    role: "USER",
  },
  {
    id: 7,
    username: "user5",
    password: "123",
    accessToken: "accessToken-for-id-7",
    refreshToken: "refreshToken-for-id-7",
    role: "USER",
  },
  {
    id: 8,
    username: "user6",
    password: "123",
    accessToken: "accessToken-for-id-8",
    refreshToken: "refreshToken-for-id-8",
    role: "USER",
  },
  {
    id: 9,
    username: "user7",
    password: "123",
    accessToken: "accessToken-for-id-9",
    refreshToken: "refreshToken-for-id-9",
    role: "USER",
  },
  {
    id: 10,
    username: "user8",
    password: "123",
    accessToken: "accessToken-for-id-10",
    refreshToken: "refreshToken-for-id-10",
    role: "USER",
  },
];
